### PR TITLE
ADD Audit entry filterBy

### PR DESCRIPTION
**Pull request by kl3sk**
Add possibility to filter by "event" when fetching Entries

### CODE REVIEW

**Comment by kl3sk** [comment]
fixer was run, but first I have conflict as you see then if change some files I don't touch.

**Comment by DamienHarper** [comment]
Sorry, I forgot to tell you: please, do run the fixer on your code only.
I'll exclude some of them such as `src/DoctrineAuditBundle/DependencyInjection/Configuration.php` later so you can run the fixer on the whole project.

**Comment by kl3sk** [comment]
Better ?

**Comment by kl3sk** [comment]
I forgot to update the readme, I should think of it 😃.

**Pull request merged**
