### PR TITLE
Security annotation

### PR DESCRIPTION
**Pull request by DamienHarper**

### CODE REVIEW

**Comment by maxhelias** [comment]
What do you think about using a security attribute instead a new annotation ? 
This would bring together the entire configuration for an entity. Then it will remain more than "ignored_columns"

**Comment by DamienHarper** [comment]
@maxhelias well I thought about using a property of `Auditable` annotation but found more intuitive/developer friendly to have a dedicated annotation to add a column to the ignored list.
So I followed the same principle here and keep things separated: `ignored_colums` is handled by the `Ignore` annotation and security by a `Secuity` annotation.

**Comment by n3o77** [comment]
@DamienHarper could you please provide some docs how the config has to look for this? Since the update I can't access any audits anymore.

**Comment by DamienHarper** [comment]
@n3o77 it’s in the work, will be available soon

**Comment by DamienHarper** [comment]
@n3o77 checkout PR #100 (Revamped documentation)
Still a work in progress but you can find some explanations about annotations [here](https://github.com/DamienHarper/DoctrineAuditBundle/pull/100/files#diff-f4bf3295d15d17279a64ceda757fce9e)
You can also have look at concrete usage in: 
- `tests/DoctrineAuditBundle/Fixtures/Core/Annotation/AuditedEntity.php`
- `tests/DoctrineAuditBundle/Fixtures/Core/Annotation/UnauditedEntity.php`

**Pull request merged**
