### PR TITLE
Solves phpstan raising a warning

### PR DESCRIPTION
**Pull request by patrickmatsumura**
Fixes the return type of a method in a test class that causes phpstan to raise a warning.

### CODE REVIEW

**Comment by DamienHarper** [comment]
What kind of warning does PHPStan raises on your side? It's completely fine for me: 
`composer phpstan` which runs phpstan with level 7 does not complain
```bash
$ composer phpstan
> vendor/bin/phpstan analyse src
Note: Using configuration file /Volumes/Data/Projects/others/DoctrineAuditBundle/phpstan.neon.
 34/34 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 [OK] No errors                                                                 

```

Also, it is weird that PHPStan does complain about the return type of `CleanAuditLogsCommandTest::createCommand()` but does not complain with `UpdateSchemaCommandTest::createCommand()` which has the same return type.

**Comment by patrickmatsumura** [comment]
```
$ vendor/bin/phpstan analyze tests/DoctrineAuditBundle/Command/UpdateSchemaCommandTest.php 
Note: Using configuration file /Users/patrickmatsumura/projects/DoctrineAuditBundle/phpstan.neon.
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ---------------------------------------------------------------------------------- 
  Line   UpdateSchemaCommandTest.php                                                       
 ------ ---------------------------------------------------------------------------------- 
  28     Call to an undefined method Symfony\Component\Console\Command\Command::unlock().  
  45     Call to an undefined method Symfony\Component\Console\Command\Command::unlock().  
 ------ ---------------------------------------------------------------------------------- 

                                                                                                                        
 [ERROR] Found 2 errors
```
Sorry, I've missed that file and will add a commit to the PR. 

The command `composer phpstan` doesn't catch the errors because PHPStan isn't asked to analyze files in `tests/`. My IDE is setup to check PHP files on save with the max level. That's how I noticed the errors.

After analyzing the folder `tests`, I can see a lot more errors. I'm not quite sure how you want to proceed here. Any suggestions?

**Comment by DamienHarper** [comment]
Well I think I understand: you are very likely using the latest PHPStan (0.12.x) which is much more strict regarding typehints. 
I started to work on another branch using this newer version and you're right, there are plenty of new warnings.

**Comment by patrickmatsumura** [comment]
```
$ vendor/bin/phpstan -V            
PHPStan - PHP Static Analysis Tool 0.11.19
```
I'm using the version that gets installed through composer. Also, my globally installed version of PHPStan, which is being used by my IDE, is 0.11.19. Which version are you using?

**Comment by DamienHarper** [comment]
Oh I missed the point: you're right, `composer phpstan` doesn't analyse `tests/` directory.

**Pull request merged**
